### ISSUE TITLE
As a developer I want to be able to serialize data back to JSON so I can persist the data

### ISSUE THREAD

**Issue by mike-burns** [phadej/github#9]
Suggestion by @joeyh: implement ToJSON for each data type.

**Comment by phadej** [comment]
For the persistence the auto-derived `Binary` instances might be enough?

**Comment by phadej** [comment]
I added `Binary` instances, which can be used for persisting results.

**Comment by phadej** [comment]
[`github-0.14.0`](http://hackage.haskell.org/package/github-0.14.0) released

**Comment by joeyh** [comment]
Won't any changes to the data structures break reading of Binary data generated with a previous version of the library?

Also, a Binary blob is much less appealing in my use case than a json object.

So, I don't feel that this has been resolved satisfactorally, and would appreciate if it could be re-opened.

If ToJson can't be provided for some reason, I'd be ok with using the new Request interface, to do the http requests myself, get the json and store it as well as passing it off to the library to be parsed. This seems perhaps doable already, I've just not worked out all the details.

**Comment by phadej** [comment]
The problem is that `FromJSON` instances do not parse all fields, so we cannot recover original JSON value from the parsed value. Especially we may start requiring some previously missed field, so forward compatibility will be lost in i.e. when changing data structures (not so badly though).

If you really need long-term value caching, storing raw Github responses would probably be most safest approach.

P.S. (*this is my personal opinionated opinion*): You could use [`Data.Binary.Tagged`](http://hackage.haskell.org/package/binary-tagged-0.1.3.0/docs/Data-Binary-Tagged.html) in conjunction with `Binary`, so the changes in the data structures would be automatically caught and stored data can be invalidated. AFAIK there are positive experience of using the library in `stack`.
